name: Valid all tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download file
      run: sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
    - name: Unzip
      run: sudo gunzip /usr/local/bin/ninja.gz
    - name: Set execute permission
      run: sudo chmod a+x /usr/local/bin/ninja
    - name: Update
      run: sudo apt update
    - name: Install Packages
      run: sudo apt install meson ninja libcriterion-dev -y
    - name: Clone Criterion
      run: git clone --recursive https://github.com/Snaipe/Criterion      
    - name: Copile Criterion 1
      run: sudo meson build 
    - name: Copile Criterion 2
      run: sudo ninja -C build    
    - name: make test
      run: make test
    - name: make
      run: make
